name: Integ-Testing

on: pull_request:
    branches: [ main ]

jobs:
  build:
    name: install
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASS }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Load environment variables
      run: echo "DB_PASS=${{ secrets.DB_PASS }}" >> $GITHUB_ENV
      env:
        DB_PASS: ${{ secrets.DB_PASS }}

    - name: Install Dependencies
      run: npm install

    - name: Setup Runner Database
      run: |
        mysql -u${{ env.DB_USER }} -h${{ env.DB_HOST }} -p${{ env.DB_PASS }} -e 'CREATE DATABASE IF NOT EXISTS db1;'
        mysql -u${{ env.DB_USER }} -h${{ env.DB_HOST }} -p${{ env.DB_PASS }} -e 'CREATE DATABASE IF NOT EXISTS db2;'

    - name: Run Tests
      env:
        DB_HOST: ${{ env.DB_HOST }}
        DB_PORT: 3306
        DB_USER: ${{ env.DB_USER }}
        DB_PASSWORD: ${{ env.DB_PASS }}
        DB_NAME: ${{ env.DB_NAME }}
      run: npm test
